excluded:
- Pods
disabled_rules:
- force_try
- line_length
- trailing_whitespace
- cyclomatic_complexity
- file_length
- function_body_length
- large_tuple
identifier_name:
 min_length:
  warning: 1
type_body_length:
  warning: 300
  error: 400
